package com.maksudsharif.camelpoc.acm.cmis.component.model;

public enum AcmCMISAction
{
    ADDFILE, ADDNEWFOLDER, COPYFILE, CREATEFOLDERBYPATH, CREATEFOLDER, DELETEFILE, DELETEFOLDER, DELETEFOLDERTREE, DOWNLOADFILE, GETFOLDER, GETOBJECTBYID, GETOBJECTBYPATH, LISTFOLDER, MOVEFILE, MOVEFOLDER, RENAMEFILE, RENAMEFOLDER, RETURNPARENT, UPDATEFILE
}
